[package]
name = "huey"
version = "0.3.2"
edition = "2021"
license = "MIT"
description = "Neovim lua color scheme generator written in Rust"
homepage = "https://github.com/oahlen/huey"

[dependencies]
anyhow = "=1.0.71"
clap = { version = "=4.2.7", features = ["derive"] }
lazy_static = "=1.4.0"
libmath = "=0.2.1"
regex = "=1.8.1"
serde = { version = "=1.0.162", features = ["derive"] }
thiserror = "=1.0.40"
toml = { version = "=0.7.3", features = ["preserve_order"] }
